const VEHICLE_TEXT: Record<string, string> = {
  Toyota: 'تويوتا',
  Lexus: 'لكزس',
  Nissan: 'نيسان',
  Honda: 'هوندا',
  Mercedes: 'مرسيدس',
  'Mercedes-Benz': 'مرسيدس بنز',
  BMW: 'بي إم دبليو',
  Audi: 'أودي',
  Ford: 'فورد',
  Chevrolet: 'شيفروليه',
  GMC: 'جي إم سي',
  Kia: 'كيا',
  Hyundai: 'هيونداي',
  Mazda: 'مازدا',
  Jeep: 'جيب',
  'Land Rover': 'لاند روفر',
  Porsche: 'بورش',
  Volkswagen: 'فولكس واجن',
  Subaru: 'سوبارو',
  Mitsubishi: 'ميتسوبيشي',
  Infiniti: 'إنفينيتي',
  Camry: 'كامري',
  Corolla: 'كورولا',
  Yaris: 'يارس',
  Avalon: 'أفالون',
  'Land Cruiser': 'لاند كروزر',
  Prado: 'برادو',
  Fortuner: 'فورتشنر',
  Hilux: 'هايلكس',
  RAV4: 'راف4',
  ES: 'إي إس',
  LS: 'إل إس',
  IS: 'آي إس',
  RX: 'آر إكس',
  LX: 'إل إكس',
  GX: 'جي إكس',
  NX: 'إن إكس',
  Patrol: 'باترول',
  Sunny: 'صني',
  Altima: 'التيما',
  Maxima: 'ماكسيما',
  'X-Trail': 'اكس تريل',
  Pathfinder: 'باثفندر',
  Accord: 'أكورد',
  Civic: 'سيفيك',
  Pilot: 'باي-لوت',
  'CR-V': 'سي آر-في',
  Sonata: 'سوناتا',
  Elantra: 'إلنترا',
  Accent: 'أكسنت',
  Tucson: 'توسان',
  'Santa Fe': 'سنتافي',
  Palisade: 'باليسيد',
  K5: 'كي 5',
  Cerato: 'سيراتو',
  Rio: 'ريو',
  Sportage: 'سبورتاج',
  Sorento: 'سورينتو',
  Telluride: 'تيلورايد',
  GLE: 'جي إل إي',
  Standard: 'قياسي',
  Stanard: 'قياسي',
  GL: 'جي إل',
  GLX: 'جي إل إكس',
  XLE: 'إكس إل إي',
  Limited: 'محدود',
  Sport: 'رياضي',
  Platinum: 'بلاتينيوم',
  Titanium: 'تيتانيوم',
  'Full Option': 'كامل المواصفات',
  Highline: 'الفئة العليا',
  Midline: 'الفئة المتوسطة',
  Baseline: 'الفئة الأساسية',
  White: 'أبيض',
  'White Pearl': 'أبيض لؤلؤي',
  Black: 'أسود',
  Silver: 'فضي',
  Gray: 'رمادي',
  Grey: 'رمادي',
  Red: 'أحمر',
  Blue: 'أزرق',
  Brown: 'بني',
  Gold: 'ذهبي',
  Green: 'أخضر',
  Petrol: 'بنزين',
  Gasoline: 'بنزين',
  Hybrid: 'هجين',
  Electric: 'كهربائي',
  Diesel: 'ديزل',
  Automatic: 'أوتوماتيك',
  Manual: 'يدوي',
  CVT: 'سي في تي',
  Saudi: 'سعودي',
  'Saudi Arabia': 'سعودي',
  KSA: 'سعودي',
  GCC: 'خليجي',
  Gulf: 'خليجي',
  'GCC Specs': 'خليجي',
  'American Import': 'وارد أمريكي',
  'US Import': 'وارد أمريكي',
  American: 'وارد أمريكي',
  European: 'وارد أوروبي',
  'European Import': 'وارد أوروبي',
  Japanese: 'وارد ياباني',
  'Japanese Import': 'وارد ياباني',
  Korean: 'وارد كوري',
  'Korean Import': 'وارد كوري',
  Chinese: 'وارد صيني',
  'Chinese Import': 'وارد صيني'
}

export function localizeVehicleText(value: string | null | undefined) {
  const text = value?.trim()
  if (!text) return ''
  return VEHICLE_TEXT[text] || VEHICLE_TEXT[text.toUpperCase()] || text
}

export function vehicleTitle(config: { make?: string | null; model?: string | null; year?: number | string | null }) {
  return [localizeVehicleText(config.make), localizeVehicleText(config.model), config.year]
    .filter(Boolean)
    .join(' ')
}
